from . import property
from . import help
from . import owner
from . import bedroom
from . import sale_order
from . import client
from . import res_partner
from . import building
from . import property_hist
from . import acount_move